export enum ResourceTypes {
  MOVIE = 'MOVIE',
  PERSON = 'PERSON',
  CUSTOMER = 'CUSTOMER',
  ROOM = 'ROOM',
  IMAGE = 'IMAGE',
  SCREENING = 'SCREENING',

  JSON_API_RESPONSE = 'JSON_API_RESPONSE',
}
