export const CUSTOMER_APPLICATION_SERVICE = 'CUSTOMER_APPLICATION_SERVICE'
export const CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY'
export const CUSTOMER_MAPPER = 'CUSTOMER_MAPPER'
export const CREDENTIAL_MAPPER = 'CREDENTIAL_MAPPER'
