/*
export enum FailureCode {
  NULL_ARGUMENT = "NULL_ARGUMENT",
  EMPTY_FIELD = "EMPTY_FIELD",
  INVALID_UUID = "INVALID_UUID",
  INVALID_FIELD_SIZE = "INVALID_FIELD_SIZE",
  INVALID_BIRTH_DATE_TOO_YOUNG = "INVALID_BIRTH_DATE_TOO_YOUNG",
  INVALID_BIRTH_DATE_TOO_OLD = "INVALID_BIRTH_DATE_TOO_OLD",
  CONTENT_INVALID_LANGUAGE = "CONTENT_INVALID_LANGUAGE",
  CONTENT_DUPLICATE_LANGUAGE = "CONTENT_DUPLICATE_LANGUAGE",
  CONTENT_MISSING_REQUIRED_LANGUAGE = "CONTENT_MISSING_REQUIRED_LANGUAGE",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
   = "INVALID_EMAIL_FORMAT",
  INVALID_GENRE = "INVALID_GENRE",
  INVALID_GENRE_COUNT = "INVALID_GENRE_COUNT",
  DATE_PAST_NOT_ALLOWED = "DATE_PAST_NOT_ALLOWED",
  DATE_EXCEEDS_MAX_FUTURE_LIMIT = "DATE_EXCEEDS_MAX_FUTURE_LIMIT",
  DATE_RANGE_TOO_LARGE = "DATE_RANGE_TOO_LARGE",

}
*/

export enum FailureCode {
  BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND",
  BOOKING_NOT_FOUND_FOR_SCREENING = "BOOKING_NOT_FOUND_FOR_SCREENING",
  BOOKING_WITH_INVAlID_TIME_INTERVAL = "BOOKING_WITH_INVAlID_TIME_INTERVAL",
  BOOKING_WITH_INVALID_TYPE = "BOOKING_WITH_INVALID_TYPE",
  BOOKING_NOT_FOUND_IN_FUTURE_SCHEDULE = "BOOKING_NOT_FOUND_IN_FUTURE_SCHEDULE",
  BOOKING_ALREADY_STARTED = "BOOKING_ALREADY_STARTED",

  CPF_WITH_INVALID_FORMAT = "CPF_WITH_INVALID_FORMAT",
  CONTENT_WITH_INVALID_TYPE = "CONTENT_WITH_INVALID_TYPE",
  CONTENT_WITH_INVALID_ITEMS = "CONTENT_WITH_INVALID_ITEMS",
  CONTENT_WITH_INVALID_FORMAT = "CONTENT_WITH_INVALID_FORMAT",

  DATE_CANNOT_BE_PAST = "DATE_CANNOT_BE_PAST",
  DATE_WITH_INVALID_SEQUENCE = "DATE_WITH_INVALID_SEQUENCE",
  DATE_OUT_OF_RANGE = "DATE_OUT_OF_RANGE",
  DATE_EXCEEDS_MAX_FUTURE_LIMIT = "DATE_EXCEEDS_MAX_FUTURE_LIMIT",
  DATE_NOT_AFTER_LIMIT = "DATE_NOT_AFTER_LIMIT",

  EMAIL_WITH_INVALID_FORMAT = "EMAIL_WITH_INVALID_FORMAT",

  GENRE_IS_DUPLICATED = "GENRE_IS_DUPLICATED",

  MISSING_REQUIRED_DATA = "MISSING_REQUIRED_DATA",

  NAME_WITH_INVALID_FORMAT = "NAME_WITH_INVALID_FORMAT",

  UID_WITH_INVALID_FORMAT = "UID_WITH_INVALID_FORMAT", // uid invalid

  VALUES_NOT_EQUAL = "VALUES_NOT_EQUAL",

  LENGTH_OUT_OF_RANGE = 'LENGTH_OUT_OF_RANGE',

  INVALID_ENUM_VALUE = "INVALID_ENUM_VALUE",
  INVALID_HYDRATE_DATA = "INVALID_HYDRATE_DATA",

  MOVIE_MISSING_CONTRIBUTORS = "MOVIE_MISSING_CONTRIBUTORS",
  MOVIE_WITHOUT_DIRECTOR = "MOVIE_WITHOUT_DIRECTOR",
  MOVIE_WITH_DURATION_TOO_SHORT = "MOVIE_WITH_DURATION_TOO_SHORT",
  MOVIE_WITH_DURATION_TOO_LONG = "MOVIE_WITH_DURATION_TOO_LONG",
  MOVIE_NOT_AVAILABLE_IN_PERIOD = "MOVIE_NOT_AVAILABLE_IN_PERIOD",
  MOVIE_ARCHIVE_BLOCKED_BY_SCREENINGS = "MOVIE_ARCHIVE_BLOCKED_BY_SCREENINGS",
  MOVIE_DELETE_BLOCKED_BY_SHOWINGS = "MOVIE_DELETE_BLOCKED_BY_SHOWINGS",

  RESOURCE_ARCHIVED = "RESOURCE_ARCHIVED",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",
  ROOM_WITH_INVALID_CAPACITY = "ROOM_WITH_INVALID_CAPACITY",
  ROOM_OPERATING_HOURS_VIOLATION = "ROOM_OPERATING_HOURS_VIOLATION",
  ROOM_NOT_AVAILABLE_FOR_SCHEDULE = "ROOM_NOT_AVAILABLE_FOR_SCHEDULE",
  ROOM_NOT_AVAILABLE_FOR_PERIOD = "ROOM_NOT_AVAILABLE_FOR_PERIOD",
  ROOM_HAS_FUTURE_BOOKINGS = "ROOM_HAS_FUTURE_BOOKINGS", // Não é possível fechar uma sala que possui agendamentos futuros
  ROOM_PERIOD_UNAVAILABLE = "ROOM_PERIOD_UNAVAILABLE", // Novo código de erro para período indisponível
  ROOM_CLOSED_FOR_BOOKING = "ROOM_CLOSED_FOR_BOOKING",

  STRING_CANNOT_BE_EMPTY = 'STRING_CANNOT_BE_EMPTY',
  STRING_CANNOT_BE_BLANK = 'STRING_CANNOT_BE_BLANK',
  STRING_INVALID_FORMAT = 'STRING_INVALID_FORMAT',
  STRING_LENGTH_OUT_OF_RANGE = 'STRING_LENGTH_OUT_OF_RANGE',
  SHOWTIME_SCHEDULE_WITH_DATE_IN_PAST = "SHOWTIME_SCHEDULE_DATE_IN_PAST",
  SHOWTIME_SCHEDULE_WITH_DATE_TOO_FAR = "SHOWTIME_SCHEDULE_DATE_TOO_FAR",
  SHOWTIME_SCHEDULE_WITH_DATE_OUTSIDE_DISPLAY_PERIOD = "SHOWTIME_SCHEDULE_DATE_OUTSIDE_DISPLAY_PERIOD",
  SHOWTIME_SCHEDULE_WITH_INVALID_MOVIE_STATUS = "SHOWTIME_SCHEDULE_WITH_INVALID_MOVIE_STATUS",
  SHOWTIME_WITH_INVALID_STATUS_TRANSITION = "SHOWTIME_WITH_INVALID_STATUS_TRANSITION",
  SCREENING_CANCELLED_STATUS_CHANGE_FORBIDDEN = "SCREENING_CANCELLED_STATUS_CHANGE_FORBIDDEN",
  SCREENING_FINALIZED_STATUS_CHANGE_FORBIDDEN = "SCREENING_FINALIZED_STATUS_CHANGE_FORBIDDEN",
  SCREENING_INVALID_DIRECT_FINALIZATION = "SCREENING_INVALID_DIRECT_FINALIZATION",
  SCREENING_CANNOT_CANCEL_ACTIVE_OR_FINALIZED = "SCREENING_CANNOT_CANCEL_ACTIVE_OR_FINALIZED",
  SCREENING_CANNOT_START = "SCREENING_CANNOT_START",
  SCREENING_NOT_IN_SHOWING_PERIOD = "SCREENING_NOT_IN_SHOWING_PERIOD",
  SCREENING_NOT_AVAILABLE_FOR_BOOKING = "SCREENING_NOT_AVAILABLE_FOR_BOOKING",
  SCREENING_NOT_AVAILABLE_FOR_BOOKING_CANCELLATION = "SCREENING_NOT_AVAILABLE_FOR_BOOKING_CANCELLATION",

  VALUE_OUT_OF_RANGE = 'VALUE_OUT_OF_RANGE',
  VALUE_GREATER_THAN_MAX = 'VALUE_GREATER_THAN_MAX',
  VALUE_LESS_THAN_MIN = 'VALUE_LESS_THAN_MIN',
  VALUE_NOT_POSITIVE = 'VALUE_NOT_POSITIVE',
  VALUE_CANNOT_BE_NEGATIVE = 'VALUE_CANNOT_BE_NEGATIVE',
  VALUE_NOT_INTEGER = 'VALUE_NOT_INTEGER',

  UNCATALOGUED_ERROR = "UNCATALOGUED_ERROR",

  // NÃO POSSUEM CÓDIGO...
  // INVALID_LANGUAGE = 'INVALID_LANGUAGE',

  // OBJECT_MISSING_PROPERTY = 'OBJECT_MISSING_PROPERTY',
  // OBJECT_IS_EMPTY = 'OBJECT_IS_EMPTY',
  // DATE_NOT_BEFORE_LIMIT = 'DATE_NOT_BEFORE_LIMIT',
  // INVALID_SEAT_ROW = 'INVALID_SEAT_ROW',
  // TEXT_DUPLICATED_FOR_LANGUAGE = 'TEXT_DUPLICATED_FOR_LANGUAGE',
  // TEXT_LANGUAGE_REQUIRED = 'TEXT_LANGUAGE_REQUIRED',
  // MOVIE_NOT_AVAILABLE_FOR_VIEWING = "MOVIE_NOT_AVAILABLE_FOR_VIEWING",
  // MOVIE_NOT_AVAILABLE_FOR_SCHEDULE_IN_PROVIDED_PERIOD = "MOVIE_NOT_AVAILABLE_FOR_SCHEDULE_IN_PROVIDED_PERIOD",

  MISSING_VALID_ITEM = "MISSING_VALID_ITEM",
  FAILURE_TO_PERSIST_DATA = "FAILURE_TO_PERSIST_DATA",
  PREFERENTIAL_SEAT_NOT_FOUND_IN_LAYOUT = "PREFERENTIAL_SEAT_NOT_FOUND_IN_LAYOUT",
  INVALID_SEAT_COLUMN = "INVALID_SEAT_COLUMN",
  SEAT_COLUMN_OUT_OF_RANGE = "SEAT_COLUMN_OUT_OF_RANGE",
  PREFERENTIAL_SEATS_LIMIT_EXCEEDED = "PREFERENTIAL_SEATS_LIMIT_EXCEEDED",
  PREFERENTIAL_SEAT_NOT_IN_ROW = "PREFERENTIAL_SEAT_NOT_IN_ROW",
  INVALID_NUMBER_OF_PREFERENTIAL_SEATS = "INVALID_NUMBER_OF_PREFERENTIAL_SEATS",
  UNAUTHORIZED_BOOKING_CANCELLATION = "UNAUTHORIZED_BOOKING_CANCELLATION",
  INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION",
  INVALID_SCREENING_DURATION = "INVALID_SCREENING_DURATION",
  INVALID_OPERATION_DURATION = "INVALID_OPERATION_DURATION",
  INVALID_MAINTENANCE_DURATION = "INVALID_MAINTENANCE_DURATION",
  MISSING_EXIT_PERIOD = "MISSING_EXIT_PERIOD",
  INSUFFICIENT_TIME_BETWEEN_SCREENINGS = "INSUFFICIENT_TIME_BETWEEN_SCREENINGS",
  CLEANING_ASSOCIATED_WITH_SCREENING = "CLEANING_ASSOCIATED_WITH_SCREENING",
  INVALID_BOOKING_TYPE_FOR_REMOVAL = "INVALID_BOOKING_TYPE_FOR_REMOVAL",
  INVALID_ACTIVITY_TYPE = "INVALID_ACTIVITY_TYPE",
  ACTIVITY_DURATION_TOO_SHORT = "ACTIVITY_DURATION_TOO_SHORT",
  ACTIVITY_DURATION_TOO_LONG = "ACTIVITY_DURATION_TOO_LONG",
  OVERLAPPING_ACTIVITIES = "OVERLAPPING_ACTIVITIES",
  DUPLICATE_PREFERENTIAL_SEAT = "DUPLICATE_PREFERENTIAL_SEAT",
  SEAT_ALREADY_BOOKED = "SEAT_ALREADY_BOOKED",
  SEAT_DOES_NOT_EXIST = "SEAT_DOES_NOT_EXIST",
  SEAT_NOT_BOOKED = "SEAT_NOT_BOOKED",
  VALIDATOR_WITH_INVALID_DATA_STRUCTURE = "VALIDATOR_WITH_INVALID_DATA_STRUCTURE",
}

/*

- Sempre utilize placeholders como {resource},
 {action} ,
  {field} ,
  {min} ,
  {max} ,
  {uuid} ,
  {value} ,
 etc., conforme o contexto do erro.
*/
